name: ccarev2_frontend
version: 1.7.5+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  aligned_dialog: ^0.0.6
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  emoji_picker_flutter: ^1.1.1
  firebase_auth: ^4.2.9
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^15.1.0+1
  flutter_speed_dial: ^7.0.0
  google_maps_flutter: ^2.0.11
  image_picker: ^1.0.1
  location: ^5.0.0
  path: any
  path_provider: any
  scoped_model: ^2.0.0
  sizer: ^2.0.15
  socket_io_client: ^2.0.0-beta.2
  url_launcher: any
  encrypt: ^5.0.1
  video_player: ^2.2.18
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.2
  flutter_rating_bar: ^4.0.0
  flutter_svg: any
  font_awesome_flutter: any
  google_fonts: any
  google_sign_in: any
  http: ^0.13.3
  shared_preferences: any
  timelines: ^0.1.0
  transparent_image: any
  common: 
    path: ./common
  flutter_test: 
    sdk: flutter

flutter_icons: 
  image_path: assets/icon/icon.png
  android: true
  ios: true

flutter: 
  assets: 
    - assets/
    - assets/images/
    - assets/icons/
    - assets/icon/
  uses-material-design: true

