// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB70c6JFq_VZDQpOwaydqrCby_XVbNyKKI',
    appId: '1:797374976435:web:c4dab694ff35ea28d27bc6',
    messagingSenderId: '797374976435',
    projectId: 'cardiocare-9c267',
    authDomain: 'cardiocare-9c267.firebaseapp.com',
    storageBucket: 'cardiocare-9c267.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAETuHg9gqL7-feu3GdMmc4UEH3bjabZr4',
    appId: '1:797374976435:android:fc764f328698da40d27bc6',
    messagingSenderId: '797374976435',
    projectId: 'cardiocare-9c267',
    storageBucket: 'cardiocare-9c267.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdCkwd8hdE-tl84LQAGG6nSgicN2EJRdo',
    appId: '1:797374976435:ios:9e5ec16a3e816da6d27bc6',
    messagingSenderId: '797374976435',
    projectId: 'cardiocare-9c267',
    storageBucket: 'cardiocare-9c267.appspot.com',
    androidClientId: '797374976435-2i2nd9ucupsujbpfh6784n4e7mb07n6a.apps.googleusercontent.com',
    iosClientId: '797374976435-apq1kjghvso51hgaejreh837uec0f3tk.apps.googleusercontent.com',
    iosBundleId: 'com.cardio.care',
  );
}
